### ISSUE TITLE
AI container cannot run properly

### ISSUE THREAD

**Issue by VimForLaNie** [VimForLaNie/Pdairy#19]
pdairy-ai-1         | Traceback (most recent call last):
pdairy-ai-1         |   File "main.py", line 12, in <module>
pdairy-ai-1         |     model = tf.keras.models.load_model('model_save')
pdairy-ai-1         |   File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/saving_api.py", line 238, in load_model 
pdairy-ai-1         |     return legacy_sm_saving_lib.load_model(
pdairy-ai-1         |   File "/usr/local/lib/python3.8/dist-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
pdairy-ai-1         |     raise e.with_traceback(filtered_tb) from None
pdairy-ai-1         |   File "/usr/local/lib/python3.8/dist-packages/keras/src/saving/legacy/saved_model/load.py", line 113, in load
pdairy-ai-1         |     raise IOError(
pdairy-ai-1         | OSError: Cannot parse keras metadata at path model_save/keras_metadata.pb: Received error: Error parsing message
pdairy-ai-1 exited with code 0

@Rmjp

**Comment by Rmjp** [comment]
ผมรันได้นะ
ลอง `pip freeze` ดู

**Comment by Rmjp** [comment]
`absl-py==1.4.0
astunparse==1.6.3
blinker==1.6.2
cachetools==5.3.1
certifi==2023.7.22
charset-normalizer==3.2.0
click==8.1.7
Flask==2.3.3
flatbuffers==23.5.26
gast==0.4.0
google-auth==2.23.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.58.0
h5py==3.9.0
idna==3.4
importlib-metadata==6.8.0
itsdangerous==2.1.2
Jinja2==3.1.2
keras==2.13.1
libclang==16.0.6
Markdown==3.4.4
MarkupSafe==2.1.3
numpy==1.24.3
oauthlib==3.2.2
opt-einsum==3.3.0
packaging==23.1
protobuf==4.24.3
pyasn1==0.5.0
pyasn1-modules==0.3.0
requests==2.31.0
requests-oauthlib==1.3.1
rsa==4.9
scipy==1.11.2
six==1.16.0
tensorboard==2.13.0
tensorboard-data-server==0.7.1
tensorflow==2.13.0
tensorflow-cpu-aws==2.13.0
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.34.0
termcolor==2.3.0
typing_extensions==4.5.0
urllib3==1.26.16
Werkzeug==2.3.7
wrapt==1.15.0
zipp==3.16.2`

**Comment by Rmjp** [comment]
Build docker ใหม่ก่อนนะ ผมเปลี่ยน image #20

**Comment by Rmjp** [comment]
#20

**Comment by Rmjp** [comment]
https://github.com/soCzech/TransNetV2/issues/6#issue-688850584
เหมือนไฟล์จะพังนะ ลองอัพใหม่ดู ผมรันในคอมก็ผ่าน แต่เดี๋ยว zipให้

**Comment by Rmjp** [comment]
เหมือนไฟล์พังนะ เดี๋ยวผม zip ให้ เพราะผมรันใน pc ก็ได้
